services:
  - type: web
    name: lts-recruiting-server
    env: node
    buildCommand: |
      cd server
      npm install
      npm install -g typescript
      tsc --version
      tsc
      ls -la dist/
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production 