services:
  - type: web
    name: lts-recruiting-server
    env: node
    buildCommand: |
      cd server
      echo "Current directory: $(pwd)"
      echo "Installing dependencies..."
      npm install
      echo "Installing TypeScript..."
      npm install typescript --save-dev
      echo "TypeScript version:"
      npx tsc --version
      echo "Compiling TypeScript..."
      npx tsc
      echo "Contents of current directory:"
      ls -la
      echo "Contents of dist directory:"
      ls -la dist/
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production 