services:
  - type: web
    name: lts-recruiting-server
    env: node
    buildCommand: |
      cd /opt/render/project/src/server
      npm install
      npm install typescript @types/node --save-dev
      npx tsc --project tsconfig.json
      ls -la dist/
    startCommand: cd /opt/render/project/src/server; node --max-old-space-size=1024 dist/index.js
    envVars:
      - key: NODE_ENV
        value: production 