services:
  - type: web
    name: lts-recruiting-server
    env: node
    buildCommand: |
      cd server
      chmod +x build.sh
      ./build.sh
    startCommand: cd server && node --max-old-space-size=1024 dist/index.js
    envVars:
      - key: NODE_ENV
        value: production 