services:
  - type: web
    name: lts-recruiting-server
    env: node
    buildCommand: |
      cd server
      chmod +x build.sh
      ./build.sh
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production 